print("please enter your name")
a = input()
print("please enter your crush`s name")
b = input()
print("please enter your favourite destination")
c = input()
print("please enter your favourite food")
d = input()
print("{} with his/her crush {} went on a date to {} . {} ate {} and had fun with {} . {} was impressed by {} as he/she payed attention to her . she/he thought that he is the right guy/girl for her/him and she/he accepted {}'s proposal and now there relationship started".format(a,b,c,a,d,b,b,a,a))
e = input()
